services:
  frontendcontainer:
    image: pricewise/image
    build: 
      context: ./ 
      dockerfile: frontend.dockerFile
    ports:
      - 3000:3000
      - 80:80
      - 443:443
    depends_on:
      mongodbcontainer:
          condition: service_healthy
    

  
  mongodbcontainer:
    image: mongo:8.0.0-rc11-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    healthcheck:
      test: mongosh mongodb://user:pass@mongodbcontainer:27017/?directConnection=true&serverSelectionTimeoutMS=15000&appName=mongosh+2.2.10
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 2m
    
